import { useEffect, useState } from "react";
import { ArrowRight, BellRing, Building2, CheckCircle2, ChevronRight, CircleAlert, Clock3, FileSearch, IndianRupee, ScanLine, ShieldCheck, UserRoundCheck, WalletCards } from "lucide-react";
import { lookupPlate } from "@/api/documents";
import api from "@/api/axios";

const kpis = [
  { label: "Awaiting approval", value: "16", context: "5 submitted since yesterday", icon: UserRoundCheck, tone: "amber" },
  { label: "Expiring within 30 days", value: "24", context: "8 require action this week", icon: BellRing, tone: "rose" },
  { label: "Vehicles compliant", value: "186 / 204", context: "91.2% fleet coverage", icon: ShieldCheck, tone: "green" },
  { label: "Invoices awaiting payment", value: "12", context: "₹4.86L outstanding", icon: WalletCards, tone: "blue" },
];
const queue: { type:string; title:string; detail:string; owner:string; due:string; level:string; action:string; color:string }[] = [];
const expiries: [string, string, string, boolean][] = [];
const audits: [string, string, string, string][] = [];
const toneClasses: Record<string, string> = { amber: "bg-amber-50 text-amber-800 ring-amber-200", rose: "bg-rose-50 text-rose-800 ring-rose-200", green: "bg-emerald-50 text-emerald-800 ring-emerald-200", blue: "bg-sky-50 text-sky-800 ring-sky-200" };

export function DashboardPage() {
  const [filter, setFilter] = useState("All"); const [plate, setPlate] = useState(""); const [matched, setMatchedState] = useState<boolean | null>(null); const [vehicleName, setVehicleName] = useState(""); const [notice, setNotice] = useState("");
  const shownQueue = filter === "All" ? queue : queue.filter((item) => item.type === filter);
  const announce = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3000); };
  const [liveKpis, setLiveKpis] = useState(kpis);
  useEffect(() => { void api.get("/reports/summary").then(({data}) => setLiveKpis([{...kpis[0], value:String(data.pending_approvals)}, {...kpis[1], value:"—"}, {...kpis[2], value:String(data.active_vehicles)}, {...kpis[3], value:String(data.invoice_total)}])).catch(console.error); }, []);
  const verifyPlate = async () => { try { const result = await lookupPlate(plate); setMatchedState(Boolean(result.vehicle)); setVehicleName(result.vehicle ? `${result.vehicle.make ?? ""} ${result.vehicle.model ?? result.vehicle.vehicle_type}`.trim() : ""); } catch { setMatchedState(false); setVehicleName(""); } };
  const setMatched = (value: boolean) => { setMatchedState(value); void verifyPlate(); };
  return <div className="mx-auto w-full max-w-[1500px] space-y-5 pb-8">
    {notice && <div role="status" className="fixed right-5 top-20 z-50 rounded-lg border border-brand-border bg-brand-forest px-4 py-3 text-sm font-medium text-white shadow-xl">{notice}</div>}
    <header className="flex flex-col gap-4 border-b border-brand-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="m-0 text-xs font-bold uppercase tracking-[0.18em] text-brand-gold-dark">Monday, 3 August 2026 · Operations desk</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-brand-forest md:text-3xl">Operations overview</h1><p className="mb-0 mt-1 text-sm text-brand-muted">Your morning control tower for vendor, fleet and payment readiness.</p></div><button onClick={() => announce("Vendor onboarding form opened")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-forest px-4 py-2.5 text-sm font-bold text-white transition hover:bg-brand-forest-light focus:outline-none focus:ring-2 focus:ring-brand-gold focus:ring-offset-2"><Building2 size={17}/> Add vendor</button></header>
    <section aria-label="Operational metrics" className="grid gap-px overflow-hidden rounded-xl border border-brand-border bg-brand-border sm:grid-cols-2 xl:grid-cols-4">{liveKpis.map(({ label, value, context, icon: Icon, tone }) => <article key={label} className="bg-white p-4"><div className="flex items-start justify-between"><p className="m-0 text-sm font-semibold text-brand-text">{label}</p><span className={`grid h-8 w-8 place-items-center rounded-md ${toneClasses[tone]}`}><Icon size={16}/></span></div><p className="mb-1 mt-5 text-2xl font-semibold tracking-tight text-brand-forest">{value}</p><p className="m-0 text-xs text-brand-muted">{context}</p></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.85fr)]"><article className="overflow-hidden rounded-xl border border-brand-border bg-white shadow-sm"><div className="border-b border-brand-border px-5 pb-0 pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="h-5 w-1 rounded-full bg-brand-gold"/><h2 className="m-0 text-lg font-semibold text-brand-forest">Priority queue</h2></div><p className="mb-0 mt-1 text-sm text-brand-muted">The actions that move the operation forward today.</p></div><span className="rounded-full bg-brand-background px-3 py-1 text-xs font-bold text-brand-forest">{shownQueue.length} open</span></div><div className="mt-4 flex gap-1 overflow-x-auto">{["All", "Approval", "OCR exception", "Vehicle compliance", "Reconciliation"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap border-b-2 px-3 py-2.5 text-xs font-bold transition ${filter === item ? "border-brand-forest text-brand-forest" : "border-transparent text-brand-muted hover:text-brand-forest"}`}>{item}</button>)}</div></div><ol className="m-0 list-none divide-y divide-brand-border p-0">{shownQueue.map((item, i) => <li key={item.title} className="group relative grid gap-3 px-5 py-4 sm:grid-cols-[28px_minmax(0,1fr)_auto] sm:items-center"><div className="relative hidden h-full sm:block"><span className={`relative z-10 grid h-7 w-7 place-items-center rounded-full text-xs font-bold ring-4 ring-white ${toneClasses[item.color]}`}>{i + 1}</span>{i < shownQueue.length - 1 && <span className="absolute left-[13px] top-7 h-[calc(100%+10px)] w-px bg-brand-border"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-wider text-brand-muted">{item.type}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ring-1 ring-inset ${toneClasses[item.color]}`}>{item.level}</span></div><h3 className="mb-1 mt-1 text-sm font-bold text-brand-text">{item.title}</h3><p className="m-0 text-xs leading-5 text-brand-muted">{item.detail}</p></div><div className="flex items-center gap-2 sm:flex-col sm:items-end"><span className="mr-auto flex items-center gap-1 text-xs font-medium text-brand-muted sm:mr-0"><Clock3 size={13}/>{item.due}</span><span className="grid h-7 w-7 place-items-center rounded-full bg-brand-forest text-[10px] font-bold text-white">{item.owner}</span><button onClick={() => announce(`${item.action}: ${item.title}`)} className="inline-flex items-center gap-1 text-xs font-bold text-brand-gold-dark hover:text-brand-forest focus:outline-none focus:underline">{item.action}<ChevronRight size={14}/></button></div></li>)}</ol></article>
      <div className="space-y-5"><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="m-0 text-base font-semibold text-brand-forest">Document expiry watch</h2><p className="mb-0 mt-1 text-xs text-brand-muted">RC, insurance and vendor KYC</p></div><CircleAlert className="text-brand-gold-dark" size={19}/></div><div className="mt-4 divide-y divide-brand-border">{expiries.map(([name, vendor, date, urgent]) => <button key={String(name)} onClick={() => announce(`Opening ${name}`)} className="flex w-full items-center gap-3 py-3 text-left"><span className={`h-2 w-2 shrink-0 rounded-full ${urgent ? "bg-rose-500" : "bg-brand-gold"}`}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-brand-text">{name}</span><span className="block truncate text-[11px] text-brand-muted">{vendor}</span></span><span className={`text-[11px] font-bold ${urgent ? "text-rose-700" : "text-brand-gold-dark"}`}>{date}</span></button>)}</div><button className="mt-2 text-xs font-bold text-brand-forest hover:underline">View compliance register <ArrowRight className="inline" size={13}/></button></article>
      <article className="rounded-xl border border-brand-border bg-[#fbfaf6] p-5 shadow-sm"><div className="flex items-center gap-2"><ScanLine className="text-brand-forest" size={19}/><h2 className="m-0 text-base font-semibold text-brand-forest">Vehicle verification</h2></div><p className="mb-3 mt-1 text-xs leading-5 text-brand-muted">Check a number plate against your internal vehicle records.</p><div className="flex gap-2"><input value={plate} onChange={(e) => setPlate(e.target.value.toUpperCase())} aria-label="Vehicle plate" className="min-w-0 flex-1 rounded-md border border-brand-border bg-white px-3 py-2 text-sm font-bold uppercase tracking-wide text-brand-text outline-none focus:border-brand-forest"/><button onClick={() => setMatched(plate.replaceAll(" ", "") === "MH12QP7842")} aria-label="Check plate" className="rounded-md bg-brand-forest px-3 text-white hover:bg-brand-forest-light"><ScanLine size={17}/></button></div>{matched ? <div className="mt-3 border-l-2 border-emerald-600 bg-white p-3"><div className="flex items-center gap-1 text-xs font-bold text-emerald-800"><CheckCircle2 size={14}/> Internal record match</div><p className="mb-0 mt-1 text-xs text-brand-muted"><b className="text-brand-text">Tata Prima 5530</b> · Northstar Logistics<br/>Insurance expires 04 Aug 2026</p></div> : <div className="mt-3 border-l-2 border-amber-500 bg-white p-3 text-xs text-brand-muted">No internal vehicle record matches this plate.</div>}</article></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="m-0 text-base font-semibold text-brand-forest">Financial snapshot</h2><p className="mb-0 mt-1 text-xs text-brand-muted">July collections · invoice payment tracking</p></div><IndianRupee className="text-brand-gold-dark" size={19}/></div><p className="mb-4 mt-5 text-2xl font-semibold text-brand-forest">₹12.48L <span className="text-xs font-medium text-emerald-700">+8.4% collected</span></p><div className="space-y-3">{[["Paid", "₹9.12L", "73", "bg-emerald-600"], ["Processing", "₹2.14L", "17", "bg-brand-gold"], ["Overdue", "₹1.22L", "10", "bg-rose-500"]].map(([label, value, width, color]) => <div key={label}><div className="flex justify-between text-xs"><span className="font-bold text-brand-text">{label}</span><span className="text-brand-muted">{value}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded bg-brand-background"><div className={`h-full ${color}`} style={{width: `${width}%`}}/></div></div>)}</div><button onClick={() => announce("Opening invoices and billing")} className="mt-5 text-xs font-bold text-brand-forest hover:underline">Open invoices & billing <ArrowRight className="inline" size={13}/></button></article><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="m-0 text-base font-semibold text-brand-forest">Recent audit activity</h2><p className="mb-0 mt-1 text-xs text-brand-muted">A traceable record of operational change</p></div><FileSearch className="text-brand-gold-dark" size={19}/></div><div className="mt-3 divide-y divide-brand-border">{audits.map(([initials, action, subject, when]) => <div key={subject} className="flex gap-3 py-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-background text-[10px] font-bold text-brand-forest">{initials}</span><p className="m-0 min-w-0 flex-1 text-xs leading-5 text-brand-muted"><span className="font-bold text-brand-text">{action}</span><br/><span className="font-medium text-brand-forest">{subject}</span></p><span className="whitespace-nowrap text-[11px] text-brand-muted">{when}</span></div>)}</div><button className="mt-2 text-xs font-bold text-brand-forest hover:underline">View audit history <ArrowRight className="inline" size={13}/></button></article></section>
  </div>;
}
