import { ArrowLeft, Building2, Mail, MapPin, Pencil, Phone, Star, Trash2 } from "lucide-react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { useVendors } from "@/contexts/VendorContext";

export function VendorDetailsPage() {
  const { id="" }=useParams(); const navigate=useNavigate(); const { getVendor,deleteVendor }=useVendors(); const vendor=getVendor(id);
  if (!vendor) return <Navigate to="/vendors" replace/>;
  const info=[["Vendor code",vendor.code],["Category",vendor.category],["GSTIN",vendor.gstin||"Not provided"],["Registered on",vendor.registeredOn]];
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><Link to="/vendors" className="rounded-lg border border-brand-border bg-white p-2 text-brand-muted hover:bg-brand-background"><ArrowLeft className="h-5 w-5"/></Link><div><h1 className="m-0 text-2xl font-semibold text-brand-forest">{vendor.name}</h1><p className="mb-0 mt-1 text-sm text-brand-muted">{vendor.code} · {vendor.category}</p></div></div><div className="flex gap-2"><button onClick={async()=>{if(window.confirm(`Delete ${vendor.name}`)){await deleteVendor(id);navigate("/vendors");}}} className="inline-flex h-10 items-center gap-2 rounded-lg border border-red-200 bg-white px-4 text-sm font-medium text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/>Delete</button><Link to={`/vendors/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-forest px-4 text-sm font-medium text-white no-underline hover:bg-brand-forest-light"><Pencil className="h-4 w-4"/>Edit vendor</Link></div></header>
  <section className="grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><aside className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-brand-background text-xl font-semibold text-brand-forest">{vendor.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><h2 className="mb-0 mt-4 text-lg font-semibold">{vendor.name}</h2><span className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">{vendor.status}</span><div className="mt-5 space-y-3 border-t border-brand-border pt-5 text-sm"><p className="flex items-center gap-2"><Mail className="h-4 w-4 text-brand-muted"/>{vendor.email}</p><p className="flex items-center gap-2"><Phone className="h-4 w-4 text-brand-muted"/>{vendor.phone}</p><p className="flex items-start gap-2"><MapPin className="mt-0.5 h-4 w-4 text-brand-muted"/>{vendor.address}, {vendor.city}, {vendor.state}</p><p className="flex items-center gap-2"><Star className="h-4 w-4 fill-brand-gold text-brand-gold"/>{vendor.rating || "Not rated"}</p></div></aside>
  <div className="space-y-5"><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-brand-forest"/><h2 className="m-0 text-base font-semibold text-brand-forest">Company information</h2></div><dl className="mt-5 grid gap-5 sm:grid-cols-2">{info.map(([label,value])=><div key={label}><dt className="text-xs font-medium uppercase tracking-wide text-brand-muted">{label}</dt><dd className="m-0 mt-1 text-sm font-medium text-brand-text">{value}</dd></div>)}</dl></article><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><h2 className="m-0 text-base font-semibold text-brand-forest">Primary contact</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="m-0 text-xs text-brand-muted">Contact person</p><p className="mb-0 mt-1 text-sm font-medium">{vendor.contactPerson}</p></div><div><p className="m-0 text-xs text-brand-muted">Email</p><p className="mb-0 mt-1 text-sm font-medium">{vendor.email}</p></div><div><p className="m-0 text-xs text-brand-muted">Phone</p><p className="mb-0 mt-1 text-sm font-medium">{vendor.phone}</p></div></div></article><article className="rounded-xl border border-brand-border bg-white p-5 shadow-sm"><h2 className="m-0 text-base font-semibold text-brand-forest">Notes</h2><p className="mb-0 mt-3 text-sm leading-6 text-brand-muted">{vendor.notes||"No notes have been added."}</p></article></div></section></div>;
}
