import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ReceiptText } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { operationsApi, type VendorOption } from "@/api/operations";
import { Busy, inputClass, Panel, PageIntro, primaryButtonClass, Problem } from "@/pages/Operations/operation-ui";

export function AddInvoicePage() {
  const navigate = useNavigate(); const [vendors, setVendors] = useState<VendorOption[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void operationsApi.vendors().then(setVendors).catch(() => setError("Vendors could not be loaded. Create a vendor first.")).finally(() => setLoading(false)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(""); try { await operationsApi.createInvoice({ vendor_id:String(data.get("vendor_id")), invoice_number:String(data.get("invoice_number")), invoice_date:String(data.get("invoice_date")), due_date:String(data.get("due_date")) || undefined, amount:Number(data.get("amount")), tax_amount:Number(data.get("tax_amount") || 0) }); navigate("/invoices"); } catch { setError("Invoice could not be saved. Check the invoice number and amounts."); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-4xl space-y-5"><PageIntro eyebrow="Finance desk" title="Add invoice"><Link to="/invoices" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-forest hover:underline"><ArrowLeft className="h-4 w-4"/>Back to invoices</Link></PageIntro><Panel>{loading ? <Busy/> : error && !vendors.length ? <Problem message={error}/> : <form onSubmit={submit} className="p-5 md:p-7"><div className="mb-6 border-b border-brand-border pb-5"><h2 className="m-0 text-lg font-semibold text-brand-forest">Billing details</h2><p className="mb-0 mt-1 text-sm text-brand-muted">Create a draft invoice, then submit it for approval from the register.</p></div>{error && <p className="mb-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="grid gap-5 md:grid-cols-2"><Field label="Vendor"><select required name="vendor_id" className={inputClass}><option value="">Choose vendor</option>{vendors.map(v => <option key={v.id} value={v.id}>{v.legal_name}</option>)}</select></Field><Field label="Invoice number"><input required name="invoice_number" className={inputClass}/></Field><Field label="Invoice date"><input required name="invoice_date" type="date" className={inputClass}/></Field><Field label="Due date"><input name="due_date" type="date" className={inputClass}/></Field><Field label="Amount before tax"><input required min=".01" step=".01" name="amount" type="number" className={inputClass}/></Field><Field label="Tax amount"><input min="0" step=".01" name="tax_amount" type="number" defaultValue="0" className={inputClass}/></Field></div><div className="mt-7 flex justify-end gap-3 border-t border-brand-border pt-5"><Link to="/invoices" className="rounded-lg px-4 py-2 text-sm font-medium text-brand-muted hover:bg-brand-background">Cancel</Link><button disabled={saving} className={primaryButtonClass}><ReceiptText className="h-4 w-4"/>{saving ? "Saving…" : "Save draft"}</button></div></form>}</Panel></main>;
}
function Field({ label, children }: { label:string; children:ReactNode }) { return <label className="grid gap-1.5 text-sm font-semibold text-brand-text"><span>{label}</span>{children}</label>; }
