import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { operationsApi, type VendorOption } from "@/api/operations";
import { Busy, inputClass, Panel, PageIntro, primaryButtonClass, Problem } from "@/pages/Operations/operation-ui";

export function AddVehiclePage() {
  const navigate = useNavigate();
  const [vendors, setVendors] = useState<VendorOption[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void operationsApi.vendors().then(setVendors).catch(() => setError("Vendors could not be loaded. Create a vendor first.")).finally(() => setLoading(false)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(""); try { await operationsApi.createVehicle({ vendor_id:String(data.get("vendor_id")), registration_number:String(data.get("registration_number")), vehicle_type:String(data.get("vehicle_type")), make:String(data.get("make")) || undefined, model:String(data.get("model")) || undefined, rc_expiry:String(data.get("rc_expiry")) || undefined, insurance_expiry:String(data.get("insurance_expiry")) || undefined, status:"ACTIVE" }); navigate("/vehicles"); } catch { setError("Vehicle could not be saved. Registration numbers must be unique."); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-4xl space-y-5"><PageIntro eyebrow="Fleet control" title="Register vehicle"><Link to="/vehicles" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-forest hover:underline"><ArrowLeft className="h-4 w-4"/>Back to fleet</Link></PageIntro><Panel>{loading ? <Busy/> : error && !vendors.length ? <Problem message={error}/> : <form onSubmit={submit} className="p-5 md:p-7"><div className="mb-6 border-b border-brand-border pb-5"><h2 className="m-0 text-lg font-semibold text-brand-forest">Vehicle details</h2><p className="mb-0 mt-1 text-sm text-brand-muted">Register a vehicle and set the key compliance renewal dates.</p></div>{error && <p className="mb-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="grid gap-5 md:grid-cols-2"><Field label="Vendor"><select required name="vendor_id" className={inputClass}><option value="">Choose vendor</option>{vendors.map(v => <option key={v.id} value={v.id}>{v.legal_name}</option>)}</select></Field><Field label="Registration number"><input required name="registration_number" placeholder="MH 01 AB 1234" className={inputClass}/></Field><Field label="Vehicle type"><input required name="vehicle_type" placeholder="Truck, van, car…" className={inputClass}/></Field><Field label="Make"><input name="make" placeholder="Optional" className={inputClass}/></Field><Field label="Model"><input name="model" placeholder="Optional" className={inputClass}/></Field><Field label="RC expiry"><input name="rc_expiry" type="date" className={inputClass}/></Field><Field label="Insurance expiry"><input name="insurance_expiry" type="date" className={inputClass}/></Field></div><div className="mt-7 flex justify-end gap-3 border-t border-brand-border pt-5"><Link to="/vehicles" className="rounded-lg px-4 py-2 text-sm font-medium text-brand-muted hover:bg-brand-background">Cancel</Link><button disabled={saving} className={primaryButtonClass}><ShieldCheck className="h-4 w-4"/>{saving ? "Saving…" : "Save vehicle"}</button></div></form>}</Panel></main>;
}
function Field({ label, children }: { label:string; children:ReactNode }) { return <label className="grid gap-1.5 text-sm font-semibold text-brand-text"><span>{label}</span>{children}</label>; }
