import type { ReactNode } from "react";
import { AlertCircle, LoaderCircle, Search } from "lucide-react";

export function PageIntro({eyebrow, title, children}:{eyebrow:string; title:string; children?:ReactNode}) { return <header className="flex flex-col gap-4 border-b border-brand-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="m-0 text-[11px] font-bold uppercase tracking-[.16em] text-brand-gold-dark">{eyebrow}</p><h1 className="mb-0 mt-1 text-3xl font-semibold tracking-tight text-brand-forest">{title}</h1></div>{children}</header>; }
export function Busy(){ return <div className="grid min-h-70 place-items-center rounded-xl border border-brand-border bg-white shadow-sm"><div className="flex items-center gap-2 text-sm text-brand-muted"><LoaderCircle className="h-4 w-4 animate-spin"/>Loading live records</div></div>; }
export function Problem({message}:{message:string}){return <div className="flex min-h-48 flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-red-200 bg-red-50/40 p-6 text-center"><AlertCircle className="h-5 w-5 text-red-700"/><p className="m-0 text-sm font-medium text-red-800">{message}</p><p className="m-0 text-xs text-brand-muted">Check your API connection or your access level, then refresh.</p></div>;}
export function Empty({title, detail}:{title:string;detail:string}){return <div className="grid min-h-55 place-items-center rounded-xl bg-[#fcfbf8] p-8 text-center"><div><span className="mx-auto mb-3 block h-1 w-10 rounded-full bg-brand-gold"/><p className="m-0 font-semibold text-brand-forest">{title}</p><p className="mb-0 mt-1 max-w-sm text-sm text-brand-muted">{detail}</p></div></div>;}
export function SearchField({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}) {return <label className="flex h-10 items-center gap-2 rounded-lg border border-brand-border bg-white px-3 focus-within:border-brand-gold"><Search className="h-4 w-4 text-brand-muted"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full border-0 bg-transparent text-sm outline-none"/></label>}
export const statusClass=(status:string)=> status.includes("ACTIVE") || status.includes("APPROVED") || status.includes("PAID") ? "bg-emerald-50 text-emerald-800" : status.includes("REJECT") || status.includes("EXPIRED") ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-800";
export function Badge({status, className=""}:{status:string; className?:string}){return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusClass(status)} ${className}`}>{status.replaceAll("_"," ")}</span>;}
export function Panel({children, className=""}:{children:ReactNode; className?:string}){return <section className={`overflow-hidden rounded-xl border border-brand-border bg-white shadow-sm ${className}`}>{children}</section>;}
export function StatGrid({children}:{children:ReactNode}){return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</section>;}
export function StatCard({label, value, note}:{label:string; value:string|number; note?:string}){return <article className="flex h-24 items-center justify-between rounded-xl border border-brand-border bg-white p-4 shadow-sm"><div><p className="m-0 text-2xl font-semibold text-brand-forest">{value}</p><p className="mb-0 mt-1 text-sm font-medium">{label}</p>{note && <p className="mb-0 mt-0.5 text-xs text-brand-muted">{note}</p>}</div><div className="h-10 w-1 rounded-full bg-brand-gold"/></article>;}
export const tableHeadClass = "bg-brand-background/50 text-xs uppercase text-brand-muted";
export const inputClass = "h-10 w-full rounded-lg border border-brand-border bg-white px-3 text-sm outline-none transition focus:border-brand-forest focus:ring-2 focus:ring-brand-forest/10";
export const primaryButtonClass = "inline-flex h-10 items-center gap-2 rounded-lg bg-brand-forest px-4 text-sm font-semibold text-white hover:bg-brand-forest-light disabled:opacity-50";
export const outlineButtonClass = "inline-flex items-center gap-1 rounded-lg border border-brand-border px-2.5 py-1.5 text-xs font-semibold text-brand-forest hover:border-brand-gold";
export const date = (value?:string) => value ? new Intl.DateTimeFormat("en-IN", {day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)) : "—";
export const money = (value:number) => new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR",maximumFractionDigits:0}).format(value || 0);
